server:
  port: 8081

spring:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 10 # 하트비트 간격(기본 30초)
  #    lease-expiration-duration-in-seconds: 30 # 만료 시간(기본 90초)
  client:
    # 유레카에 자신 등록 (다른 서비스들이 검색할 수 있게) (export)
    register-with-eureka: true
    # 유레카에서 다른 서비스 목록 가져올지 여부 (import)
    fetch-registry: true
    # 유레카 서버의 위치 주소
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  # 일반 토큰 만료 시간
  expires-in: 86400 # 1day
  # 모바일용 토큰 만료 시간
  mobile-expires-in: 31536000
  # PC용 토큰 만료 시간
  table-expires-in: 31536000
  # 토큰 서명에 사용하는 비밀키
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86Ggkgkgkgkgkgkgkgk

kafka:
  bootstrap-servers: localhost:9092

